SELECT * FROM CovidDeaths$;

SELECT * FROM CovidVaccinations$;

SELECT * FROM CovidDeaths$
ORDER BY 3,4;

SELECT * FROM CovidVaccinations$
ORDER BY 3,4;

SELECT LOCATION,DATE,TOTAL_CASES,NEW_CASES,TOTAL_DEATHS,POPULATION 
FROM CovidDeaths$
ORDER BY 1,2;

--TOTAL CASES VS TOTAL DEATHS
SELECT LOCATION, DATE, TOTAL_CASES,TOTAL_DEATHS,
(TOTAL_DEATHS/TOTAL_CASES)* 100 AS DEATHSPER
FROM CovidDeaths$
ORDER BY 1,2;

SELECT LOCATION, DATE, TOTAL_CASES,TOTAL_DEATHS,
(TOTAL_DEATHS/TOTAL_CASES)* 100 AS DEATHSPER
FROM CovidDeaths$
WHERE LOCATION LIKE '%INDIA%'
ORDER BY 1,2;

--TOTAL CASES VS POPULATIONS

SELECT LOCATION, DATE, TOTAL_CASES, POPULATION,
(TOTAL_CASES/POPULATION)*100 AS POPULATIONPERCETAGE
FROM CovidDeaths$
ORDER BY 1,2;

SELECT LOCATION, DATE, TOTAL_CASES, POPULATION,
(TOTAL_CASES/POPULATION)*100 AS POPULATIONPERCETAGE
FROM CovidDeaths$
WHERE LOCATION LIKE '%INDIA%'
ORDER BY 1,2;

--COUNTRUES WITH HIGHEST INFECTION RATE COMPARED TO POPULATION

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTED,
       MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTAGEPOPULATION
FROM CovidDeaths$
GROUP BY LOCATION,POPULATION 
ORDER BY PERCENTAGEPOPULATION DESC;

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTED,
       MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTAGEPOPULATION
FROM CovidDeaths$
WHERE LOCATION LIKE '%INDIA%'
GROUP BY LOCATION,POPULATION 
ORDER BY PERCENTAGEPOPULATION DESC;

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTED,
       MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTAGEPOPULATION
FROM CovidDeaths$
WHERE LOCATION IN ('INDIA','RUSSIA')
GROUP BY LOCATION,POPULATION 
ORDER BY PERCENTAGEPOPULATION DESC;

SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTED,
       MAX(TOTAL_CASES/POPULATION)*100 AS PERCENTAGEPOPULATION
FROM CovidDeaths$
WHERE LOCATION IN ('INDIA','CHINA')
GROUP BY LOCATION,POPULATION 
ORDER BY PERCENTAGEPOPULATION DESC;

--COUNTRIES DEATH COUNT

SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHS
FROM CovidDeaths$
GROUP BY LOCATION
ORDER BY TOTALDEATHS DESC;

SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHS
FROM CovidDeaths$
WHERE LOCATION LIKE '%INDIA%'
GROUP BY LOCATION
ORDER BY TOTALDEATHS DESC;

SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTALDEATHS
FROM CovidDeaths$
WHERE LOCATION IN ('INDIA','BRAZIL','ASIA')
GROUP BY LOCATION
ORDER BY TOTALDEATHS DESC;

--LETS BREAK THINGS DOWN BY CONTINENT

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT )) AS TOTALDEATHS
FROM CovidDeaths$
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION 
ORDER BY TOTALDEATHS DESC;

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT )) AS TOTALDEATHS
FROM CovidDeaths$
WHERE CONTINENT IS NULL
GROUP BY LOCATION 
ORDER BY TOTALDEATHS DESC;

--GLOBAL NUMBERS

SELECT SUM(NEW_CASES) AS TOTAL_CASES,
       SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS,
	   SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHSPERCENTAGE
FROM CovidDeaths$
WHERE CONTINENT IS NOT NULL 
GROUP BY DATE
ORDER BY 1,2;

SELECT LOCATION,SUM(NEW_CASES) AS TOTAL_CASES,
       SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS,
	   SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATHSPERCENTAGE
FROM CovidDeaths$
WHERE CONTINENT IS NOT NULL 
GROUP BY LOCATION
ORDER BY 1,2;

SELECT * FROM CovidVaccinations$;
SELECT * FROM CovidDeaths$;

--JOIN THE DEATHS AND VACCINATIONS

SELECT * FROM CovidVaccinations$ VAC
JOIN
CovidDeaths$ DEA ON 
  VAC.LOCATION = DEA.LOCATION AND
  VAC.DATE = DEA.DATE;

  --TOTAL POPULATION VS VACCINATIONS

  SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE,
         DEA.POPULATION, VAC.NEW_VACCINATIONS
      FROM CovidVaccinations$ VAC
JOIN
     CovidDeaths$ DEA ON 
     VAC.LOCATION = DEA.LOCATION AND
     VAC.DATE = DEA.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3;


 SELECT DEA.CONTINENT, DEA.LOCATION, DEA.DATE,
         DEA.POPULATION, VAC.NEW_VACCINATIONS,
		 SUM(CONVERT(INT,VAC.NEW_VACCINATIONS))
         OVER(PARTITION BY DEA.LOCATION 
		 ORDER BY DEA.LOCATION,DEA.DATE) AS ROLLINGPEPOPLEVACCIATED
--,ROLLINGPEOPLEVACCIATED/POPULATION)*100
      FROM CovidVaccinations$ VAC
JOIN
     CovidDeaths$ DEA ON 
     VAC.LOCATION = DEA.LOCATION AND
     VAC.DATE = DEA.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY 2,3;
